force-app/main/default/objects/NZC_EmissionsMatchingConfig__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>AllowCustomTagMatching__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Should custom matching based on fields be allowed? ( overrides emissions factors from asset )</description>
        <inlineHelpText>Should custom matching based on fields be allowed? ( overrides emissions factors from asset )</inlineHelpText>
        <label>AllowCustomTagMatching</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DateMatchingField__c</fullName>
        <description>Field to match dates to emission factors on. Expecting field name ( StartDate EndDate ) or Midpoint</description>
        <inlineHelpText>Field to match dates to emission factors on. Expecting field name ( StartDate EndDate ) or Midpoint</inlineHelpText>
        <label>Date Matching Field</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DoMatchEmissionsOnInsert__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Should the emissions matching happen on insert?</description>
        <inlineHelpText>Should the emissions matching happen on insert?</inlineHelpText>
        <label>Do match emissions on insert</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DoMatchEmissionsOnUpdate__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Should emissions matching happen on record update?</description>
        <inlineHelpText>Should emissions matching happen on record update?</inlineHelpText>
        <label>Do match emissions on update</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Emissions_Matching_Batch_Size__c</fullName>
        <description>How many emissions records should be matched at once?</description>
        <inlineHelpText>How many emissions records should be matched at once?</inlineHelpText>
        <label>Emissions Matching Batch Size</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Emissions_Recalc_Batch_Size__c</fullName>
        <description>How many emission sets should be targeted at one time?</description>
        <inlineHelpText>How many emission sets should be targeted at one time?</inlineHelpText>
        <label>Emissions Recalc Batch Size</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>doLog__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Enable apex debugging messages</description>
        <inlineHelpText>Enable apex debugging messages</inlineHelpText>
        <label>do Log</label>
        <type>Checkbox</type>
    </fields>
    <label>NZC Emissions Matching Configuration</label>
</CustomObject>

force-app/main/default/objects/NZC_EmissionsMatchingCustomMatch__mdt.object
<CustomObject>
    <description>Used to match emissions sets based on criteria besides year</description>
    <fields>
        <fullName>FuelType__c</fullName>
        <description>What type of fuel does this apply for?</description>
        <inlineHelpText>What type of fuel does this apply for?</inlineHelpText>
        <label>FuelType</label>
        <length>75</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ObjectAppliesTo__c</fullName>
        <description>what object does this rule apply to?</description>
        <inlineHelpText>what object does this rule apply to?</inlineHelpText>
        <label>ObjectAppliesTo</label>
        <length>75</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>NZC_EmissionsMatchingCustomMatch</label>
    <pluralLabel>NZC_EmissionsMatchingCustomMatches</pluralLabel>
</CustomObject>

force-app/main/default/classes/NZC_EmissionsMatchingMTD.cls
/*
 * Copyright (c) 2025, Salesforce, Inc.
 * All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 * For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/Apache-2.0
 */

public with sharing class NZC_EmissionsMatchingMTD {

    public static Boolean doEmissionsMatchOnInsert {
        get {
            if (doEmissionsMatchOnInsert == null
                    && matchingConfig.get('DoMatchEmissionsOnInsert__c') != null) {
                doEmissionsMatchOnInsert = matchingConfig.DoMatchEmissionsOnInsert__c;
            }

            return doEmissionsMatchOnInsert == true? doEmissionsMatchOnInsert : false;
        }

        set {
            doEmissionsMatchOnInsert = value;
        }
    }

    public static Boolean doEmissionsMatchOnUpdate {
        get {
            if (doEmissionsMatchOnUpdate == null
                    && matchingConfig.get('DoMatchEmissionsOnUpdate__c') != null) {
                doEmissionsMatchOnUpdate = matchingConfig.DoMatchEmissionsOnUpdate__c;
            }

            return doEmissionsMatchOnUpdate == true ? doEmissionsMatchOnUpdate : false;
        }

        set {
            doEmissionsMatchOnUpdate = value;
        }
    }

    public static String dateMatchingField {
        get {
            if (String.isBlank(dateMatchingField)) {
                dateMatchingField = NZC_EmissionsMatchingConstants.FIELD_EUR_STARTDATE;
            }

            if (matchingConfig != null && String.isNotBlank(matchingConfig.DateMatchingField__c)) {
                dateMatchingField = matchingConfig.DateMatchingField__c;
            }

            return dateMatchingField;
        }

        set {
            if (Test.isRunningTest()) {
                dateMatchingField = value;
            }
        }
    }

    public static Boolean doLog {
        get {
            doLog = true;
            if (matchingConfig != null && matchingConfig.get('doLog__c') != null) {
                doLog = matchingConfig.doLog__c;
            }

            return doLog;
        }

        set {
            if (Test.isRunningTest()) {
                doLog = value;
            }
        }
    }

    public static Boolean allowCustomTagMatching {
        get {
            allowCustomTagMatching = false;
            if (matchingConfig != null && matchingConfig.get('allowCustomTagMatching__c') != null) {
                allowCustomTagMatching = matchingConfig.allowCustomTagMatching__c;
            }

            return allowCustomTagMatching;
        }

        set {
            if (Test.isRunningTest()) {
                allowCustomTagMatching = value;
            }
        }
    }

    public static Integer emissionsMatchBatchSize {
        get {
            emissionsMatchBatchSize = NZC_EmissionsMatchingConstants.EMISSIONS_MATCH_BATCH_SIZE;

            if (matchingConfig != null && matchingConfig.get('Emissions_Matching_Batch_Size__c') != null) {
                emissionsMatchBatchSize = Integer.valueOf(matchingConfig.get('Emissions_Matching_Batch_Size__c'));
            }

            return emissionsMatchBatchSize;
        }
        set;
    }

    public static Integer emissionsRecalcBatchSize {
        get {
            emissionsRecalcBatchSize = NZC_EmissionsMatchingConstants.EMISSIONS_RECALC_BATCH_SIZE;

            if (matchingConfig != null && matchingConfig.get('Emissions_Recalc_Batch_Size__c') != null) {
                emissionsRecalcBatchSize = Integer.valueOf(matchingConfig.get('Emissions_Recalc_Batch_Size__c'));
            }

            return emissionsRecalcBatchSize;
        }
        set;
    }

    public static Map<String, NZC_EmissionsMatchingCustomMatch__mdt> customMatchingRules {
        get {
            if (customMatchingRules == null) {
                customMatchingRules = getCustomMatchingRules();
            }
            return customMatchingRules;
        }
        set {
            if (Test.isRunningTest()) {
                customMatchingRules = value;
            }
        }
    }

    @TestVisible
    private static Map<String, NZC_EmissionsMatchingCustomMatch__mdt> getCustomMatchingRules() {
        Map<String, NZC_EmissionsMatchingCustomMatch__mdt> customMatchingInfo = new Map<String, NZC_EmissionsMatchingCustomMatch__mdt>();

        for (NZC_EmissionsMatchingCustomMatch__mdt rule : NZC_EmissionsMatchingCustomMatch__mdt.getAll().values()) {
            customMatchingInfo.put(NZC_EmissionsMatchingUtil.createHashKey(rule.ObjectAppliesTo__c,rule.FuelType__c), rule);
        }

        return customMatchingInfo;
    }

    @TestVisible
    private static NZC_EmissionsMatchingConfig__c matchingConfig {
        get {
            if (matchingConfig == null) {
                try {
                    matchingConfig = NZC_EmissionsMatchingConfig__c.getOrgDefaults();
                } catch (Exception e) {
                    NZC_EmissionsMatchingLog.log('error getting custom settings',e.getMessage());
                }
            }
            return matchingConfig;
        }
        set {
            if (Test.isRunningTest()) {
                matchingConfig = value;
            }
        }
    }
}